### ISSUE TITLE
Add cumulitive mitten tracking stat for users

### ISSUE THREAD

**Issue by clonk2u** [GamingWolf/WaffleIssues#12]
Keep a record of total time a person has been mittens, or keep a database record of each mittens on a user, the length of the mittens, the date, and the reason for being mittens. This will probably only be admin facing, but could be a good tool for monitoring long term user behavior for repeat offenses, or as a tool to help jump users from provisional to member.

**Comment by GamingWolf** [comment]
Waffle already does this, it is simply not accessible for non-moderators.
